# FROM node:20

# WORKDIR /app

# # Install dependencies first (better layer caching)
# COPY package*.json ./
# RUN npm install

# # Copy full source code (for production image)
# COPY . .

# EXPOSE 5000

# # Default command (used in production)
# CMD ["npm", "start"]
